/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-surface": "#e1e2eb",
              "secondary-container": "#139cc7",
              "on-primary-fixed-variant": "#004493",
              "surface": "#10131a",
              "on-secondary-container": "#002e3d",
              "tertiary": "#c2c1ff",
              "inverse-surface": "#e1e2eb",
              "on-surface-variant": "#c1c6d7",
              "on-tertiary": "#1800a7",
              "on-secondary-fixed-variant": "#004d64",
              "surface-container-low": "#191c22",
              "outline-variant": "#414755",
              "surface-dim": "#10131a",
              "error-container": "#93000a",
              "error": "#ffb4ab",
              "secondary-fixed-dim": "#68d3ff",
              "secondary": "#68d3ff",
              "outline": "#8b90a0",
              "on-primary-container": "#00285c",
              "inverse-on-surface": "#2e3037",
              "surface-tint": "#adc6ff",
              "on-error-container": "#ffdad6",
              "surface-bright": "#363940",
              "tertiary-container": "#8382ff",
              "tertiary-fixed": "#e2dfff",
              "secondary-fixed": "#bee9ff",
              "on-tertiary-fixed": "#0c006b",
              "tertiary-fixed-dim": "#c2c1ff",
              "on-background": "#e1e2eb",
              "primary-fixed-dim": "#adc6ff",
              "on-tertiary-fixed-variant": "#332dbc",
              "primary-container": "#4b8eff",
              "primary": "#adc6ff",
              "primary-fixed": "#d8e2ff",
              "inverse-primary": "#005bc1",
              "on-error": "#690005",
              "background": "#10131a",
              "on-secondary-fixed": "#001f2a",
              "on-secondary": "#003546",
              "on-tertiary-container": "#140094",
              "on-primary": "#002e69",
              "surface-container-high": "#272a31",
              "surface-container-lowest": "#0b0e14",
              "on-primary-fixed": "#001a41",
              "surface-variant": "#32353c",
              "surface-container-highest": "#32353c",
              "surface-container": "#1d2026"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "gutter": "16px",
              "margin": "24px",
              "xl": "56px",
              "xs": "4px",
              "md": "16px",
              "sm": "8px",
              "lg": "32px"
      },
      "fontFamily": {
              "label-md": ["Inter"],
              "body-md": ["Inter"],
              "body-lg": ["Inter"],
              "label-sm": ["Inter"],
              "headline-md": ["Inter"],
              "headline-lg": ["Inter"],
              "display-lg": ["Inter"]
      },
      "fontSize": {
              "label-md": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "body-md": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-lg": ["clamp(0.9rem, 1.5vw, 1rem)", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-sm": ["11px", {"lineHeight": "1.1", "fontWeight": "600"}],
              "headline-md": ["clamp(1.1rem, 2vw, 1.25rem)", {"lineHeight": "1.3", "fontWeight": "600"}],
              "headline-lg": ["clamp(1.25rem, 3vw, 1.5rem)", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-lg": ["clamp(1.75rem, 4vw, 2.25rem)", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
